# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d2ce2fbf96f1556881b9296c7f20f6d61121f4216139f64eb84a0ceeb0598a8d169cfbb2bec783e1b2d54b96135c0f16bbcde68200dbe624d09fb40eb4cdac9

test:
  secret_key_base: d8d7106e5390665366bfd0996b34bdafa99cb64db1188098b83fbe4df3624ab5adfa3118f8befd88637fab254549c6b99bda9077f1de5e88d6f9c41f15946b78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
